Stripe with npm6
sap-labs-france/ev-mobile pull request #346
Opened 2021-05-11 14:41 UTC by ClaudeROSSI

just a test - downgrade nom to v6 to have package.json in version 1

2021-05-11 16:22 UTC, jerome-benoit requested changes

2021-05-11 16:22 UTC, jerome-benoit commented on src/App.tsx
> +
Unneeded blank line

2021-05-11 16:22 UTC, jerome-benoit commented on src/App.tsx
> -
Wrong blank line removal

2021-05-12 08:18 UTC, ClaudeROSSI commented
Closing this one. Alix did the changes in the "stripe' branch

2021-05-12 08:18 UTC, closed without merging