Dev mode - tenant endpoints for testing against localhost
sap-labs-france/ev-mobile pull request #348
Opened 2021-05-13 17:15 UTC by ClaudeROSSI

I could declare tenant endpoints allowing to check the mobile app:
Strange enough but the solution is different depending on the target platform.

- With Ios, the connection to http://127.0.01 works properly
- - With ANDROID, I had to add some configuration files and target http://10.0.2.2 instead

In both cases the ev-server port is expected to be 8020

I also noticed some instability on ANDROID
- The "**Picker**" control for selecting the tenant endpoints was crashing the app. I have chanmged the code to get rid of some warnings
- The **getTenantLogo(**) was throwing an exception which was not handled property. This as been changed as well

2021-05-16 17:13 UTC, AlixH commented on src/screens/tenants/CreateTenantDialog.tsx
> +    const newTenantEndpointCloudId = tenantEndpointClouds.find((tenantEndpointCloud) => tenantEndpointCloud.id === 'scp').id;
Maybe add a chaining operator before the .id ? I think find returns undefined if nothing is found

2021-05-16 19:29 UTC, ClaudeROSSI commented on src/screens/tenants/CreateTenantDialog.tsx
> +    const newTenantEndpointCloudId = tenantEndpointClouds.find((tenantEndpointCloud) => tenantEndpointCloud.id === 'scp').id;
thanks. Done!

2021-05-18 13:19 UTC, jerome-benoit requested changes

2021-05-18 13:19 UTC, jerome-benoit commented on src/config/Configuration.tsx
> +  ];
The setup you put in there is specific to your local development environment and can't be hardcoded. You need to introduce a configuration file that permit to define custom endpoints for development purpose.

2021-05-18 13:19 UTC, jerome-benoit commented on android/app/src/main/res/xml/network_security_config.xml
> +        <domain includeSubdomains="true">10.0.2.2</domain>
We can't ship that file in the production build with a hardcoded IP address ;) 
It must be: 
+ per dev env (template)
+ tied to the development build only.

2021-05-18 13:19 UTC, jerome-benoit commented on src/screens/tenants/CreateTenantDialog.tsx
> +    const newTenantEndpointCloudId = tenantEndpointClouds.find((tenantEndpointCloud) => tenantEndpointCloud.id === 'scp')?.id;
I do not think the filtering on 'scp' is necessary. And you like to put the result of helpers in intermediate variables ;) I'm not very fond of it, I do not think that makes the code easier to read, especially with JS or TS that permits to use arrow function and the like to directly use treatment result. That's just nitpicking ;)

2021-05-18 13:45 UTC, ClaudeROSSI commented on src/screens/tenants/CreateTenantDialog.tsx
> +    const newTenantEndpointCloudId = tenantEndpointClouds.find((tenantEndpointCloud) => tenantEndpointCloud.id === 'scp')?.id;
you're right ... 'scp' is just the preferred endpoint ... so initializing the initial state using a constant is sufficient and straightforward.
I'll change it

2021-05-18 13:47 UTC, ClaudeROSSI commented on android/app/src/main/res/xml/network_security_config.xml
> +        <domain includeSubdomains="true">10.0.2.2</domain>
Right. This is the reason why this is a  DRAFT PR. 
I would need your advise on how to proceed here.

2021-05-18 14:15 UTC, ClaudeROSSI commented on src/screens/tenants/CreateTenantDialog.tsx
> +    const newTenantEndpointCloudId = tenantEndpointClouds.find((tenantEndpointCloud) => tenantEndpointCloud.id === 'scp')?.id;
done

2021-05-18 14:30 UTC, ClaudeROSSI commented on android/app/src/main/res/xml/network_security_config.xml
> +        <domain includeSubdomains="true">10.0.2.2</domain>
Configuration has been moved to:
.../android/app/src/debug/res/xml/network_security_config.xml

I'm not sure this is sufficient.

2021-06-03 07:18 UTC, ClaudeROSSI commented on assets/config-template.json
> +      "endpoint": "http://10.0.2.2:8020"
@jerome-benoit : using localhost does not work when testing with the Android emulator.
According to the documentation we have to use:
> 10.0.2.2 | Special alias to your host loopback interface

2021-07-07 10:40 UTC, ClaudeROSSI commented
One remark here for testing the mobile app against localhost.

The config file gets load thanks to:
> import ConfigurationData from '../../assets/config.json';

This file only exists when created manually (based on the provided template) and declares additional CLOUD ENDPOINTS.
I'm not sure loading a configuration file using the "import" statement is something recommended. do you?

Thanks,
Claude

2021-07-07 10:45 UTC, ClaudeROSSI commented
hi,

> npm run pod:install

does not run on my side anymore! (even with master-qa).

I'm getting:

> [!] CocoaPods could not find compatible versions for pod "Stripe":
>  In snapshot (Podfile.lock):
    Stripe (= 21.6.0, ~> 21.6.0)

>  In Podfile:
    stripe-react-native (from `../node_modules/@stripe/stripe-react-native`) was resolved to 0.1.4, which depends on
      Stripe (~> 21.6.0)

> None of your spec sources contain a spec satisfying the dependencies: `Stripe (= 21.6.0, ~> 21.6.0), Stripe (~> 21.6.0)`.

Any idea?
Thanks

2021-07-07 10:46 UTC, Ninjeneer commented
> hi,
> 
> > npm run pod:install
> 
> does not run on my side anymore! (even with master-qa).
> 
> I'm getting:
> 
> > [!] CocoaPods could not find compatible versions for pod "Stripe":
> > In snapshot (Podfile.lock):
> > Stripe (= 21.6.0, ~> 21.6.0)
> 
> > In Podfile:
> > stripe-react-native (from `../node_modules/@stripe/stripe-react-native`) was resolved to 0.1.4, which depends on
> > Stripe (~> 21.6.0)
> 
> > None of your spec sources contain a spec satisfying the dependencies: `Stripe (= 21.6.0, ~> 21.6.0), Stripe (~> 21.6.0)`.
> 
> Any idea?
> Thanks

Running npm install another time fixed it for me

2021-07-07 11:20 UTC, AlixH commented
Please do
npm clean-install
pod install in ios/ folder

From: Loan Alouache ***@***.***>
Date: Wednesday, 7 July 2021 at 12:47
To: sap-labs-france/ev-mobile ***@***.***>
Cc: HUMBERT, Alix ***@***.***>, Review requested ***@***.***>
Subject: Re: [sap-labs-france/ev-mobile] Dev mode - tenant endpoints for testing against localhost (#348)

hi,

npm run pod:install

does not run on my side anymore! (even with master-qa).

I'm getting:

[!] CocoaPods could not find compatible versions for pod "Stripe":
In snapshot (Podfile.lock):
Stripe (= 21.6.0, ~> 21.6.0)

In Podfile:
stripe-react-native (from ..***@***.***/stripe-react-native) was resolved to 0.1.4, which depends on
Stripe (~> 21.6.0)

None of your spec sources contain a spec satisfying the dependencies: Stripe (= 21.6.0, ~> 21.6.0), Stripe (~> 21.6.0).

Any idea?
Thanks

Running npm install another time fixed it for me

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/sap-labs-france/ev-mobile/pull/348#issuecomment-875500431>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AHYQUUZHB5BACQZN2EBEJYDTWQWCJANCNFSM4425MHNA>.

2021-07-07 12:23 UTC, ClaudeROSSI commented on .vscode/settings.json
> -  "workbench.colorTheme": "Solarized Dark"
I would like to remove and gitignore that file to make sure I can have a different colorTheme on my side while reviewing.
@LucasBrazi06 , @AlixH , @Ninjeneer : Is it fine with you?

2021-07-07 12:25 UTC, AlixH commented on .vscode/settings.json
> -  "workbench.colorTheme": "Solarized Dark"
I don't use VSCode ;)

2021-07-07 12:33 UTC, LucasBrazi06 commented on .vscode/settings.json
> -  "workbench.colorTheme": "Solarized Dark"
@ClaudeROSSI Okay
@AlixH Fired :-)

2021-07-07 12:46 UTC, Ninjeneer commented on .vscode/settings.json
> -  "workbench.colorTheme": "Solarized Dark"
@ClaudeROSSI I don't know if ignoring the whole file is a good idea. We could use here some useful editor settings later.

However if you want to change your VSCode style, you can still install the Solarized Dark extension, and not adding it to the .vscode/settings.json

2021-07-07 12:48 UTC, Ninjeneer commented on .vscode/settings.json
> -  "workbench.colorTheme": "Solarized Dark"
by the way, there was previously a useful setting before that fixes all eslint issues on save :
```
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  }
```

2021-07-07 13:43 UTC, merged