Invoice download
sap-labs-france/ev-mobile pull request #370
Opened 2021-06-03 13:47 UTC by AlixH

2021-06-03 13:47 UTC, AlixH commented
Should we ask permission to download a file ?

2021-06-03 15:10 UTC, LucasBrazi06 commented
> Should we ask permission to download a file ?

You mean a pop-up with yes/no (like 'Do you really want to...') ?
Why not.

2021-06-03 15:13 UTC, AlixH commented
> > Should we ask permission to download a file ?
> 
> You mean a pop-up with yes/no (like 'Do you really want to...') ?
> Why not.

I was thinking about permissions like camera access, position etc

2021-06-03 15:34 UTC, LucasBrazi06 commented
> I was thinking about permissions like camera access, position etc

Ah ok, normally you shouldn't have the choice, right?

2021-06-04 08:40 UTC, ClaudeROSSI requested changes
please check my comments

2021-06-04 08:40 UTC, ClaudeROSSI commented on package.json
> +    "rn-fetch-blob": "^0.12.0",
Can we use this one?
This the package is not maintained anymore.
@jerome-benoit : can you please advise here?

2021-06-04 08:47 UTC, AlixH commented on src/I18n/languages/de.json
> +    "invoiceFileDescription": "e-Mobility charge invoice"
Right. You see it on the file description on your phone

2021-06-04 13:03 UTC, AlixH commented on package.json
> +    "rn-fetch-blob": "^0.12.0",
I have found two forks of rn-fetch-blob (whose loss of maintenance put a loottt of people in trouble), I am having a look a it

2021-06-04 13:07 UTC, AlixH commented
> > I was thinking about permissions like camera access, position etc
> 
> Ah ok, normally you shouldn't have the choice, right?

Maybe there is a legal obligation or something ..

2021-06-04 14:56 UTC, LucasBrazi06 commented
> Maybe there is a legal obligation or something ..

The user accepts or not, simple as that.
Similar to remote push notif or localization...

2021-06-07 15:51 UTC, LucasBrazi06 requested changes

2021-06-07 15:51 UTC, LucasBrazi06 commented on src/components/invoice/InvoiceComponent.tsx
> +                <TouchableOpacity style={style.downloadButtonContainer} onPress={() => this.onPressDownload()}>
Rename 'onPressDownload' to 'downloadInvoiceConfirm'

2021-06-07 15:51 UTC, LucasBrazi06 commented on src/components/invoice/InvoiceComponent.tsx
> +      [{ text: I18n.t('general.yes'), onPress: async () => this.downloadInvoice() }, { text: I18n.t('general.cancel') }]
Not readable.
Span this line in multiple lines.

2021-06-07 15:51 UTC, LucasBrazi06 commented on src/components/invoice/InvoiceComponent.tsx
> +    const invoice = this.props.invoice;
Consistency issue:
Use like you did in line 157:
`const { invoice } = this.props;`

2021-06-07 15:51 UTC, LucasBrazi06 commented on src/provider/CentralServerProvider.tsx
> +    const url = `${this.buildRestServerURL()}/${ServerRoute.REST_BILLING_DOWNLOAD_INVOICE}`.replace(':invoiceID', invoice.id as string);
`invoice.id as string` -> `invoice.id.toString()` ?

2021-06-07 15:51 UTC, LucasBrazi06 commented on src/provider/CentralServerProvider.tsx
> +      Platform.OS === PLATFORM.IOS
Use a 'if' statement, you are not in a render() method ;-)

2021-06-07 15:51 UTC, LucasBrazi06 commented on src/provider/CentralServerProvider.tsx
> +    return res;
Return is not used right?
Return void instead?

2021-06-08 10:29 UTC, ClaudeROSSI requested changes
Small changes

2021-06-08 10:29 UTC, ClaudeROSSI commented on src/provider/CentralServerProvider.tsx
> +    const url = `${this.buildRestServerURL()}/${ServerRoute.REST_BILLING_DOWNLOAD_INVOICE}`.replace(':invoiceID', invoice.id.toString());
Could you please the helper method **buildRestEndpointUrl**() instead of calling the **buildRestEndpointUrl**(). 

The purpose is to get rid of the "string replace" and make sure the value is properly escaped when building the URL.

Several  methods like **startTransaction** are using it already.

2021-06-08 10:29 UTC, ClaudeROSSI commented on src/provider/CentralServerProvider.tsx
> +    let config = {};
I would remove the default value {}

2021-06-08 10:29 UTC, ClaudeROSSI commented on src/provider/CentralServerProvider.tsx
> +    await ReactNativeBlobUtil.config(config).fetch('GET', url, this.buildSecuredHeaders());
if would only call **ReactNativeBlobUtil** when the config is set!

2021-06-08 10:55 UTC, AlixH commented on src/provider/CentralServerProvider.tsx
> +    await ReactNativeBlobUtil.config(config).fetch('GET', url, this.buildSecuredHeaders());
I don't understand

2021-06-08 10:56 UTC, AlixH commented on src/provider/CentralServerProvider.tsx
> +    const url = `${this.buildRestServerURL()}/${ServerRoute.REST_BILLING_DOWNLOAD_INVOICE}`.replace(':invoiceID', invoice.id.toString());
I know but I'd like to do all the related changes in one dedicated PR

2021-06-08 12:42 UTC, ClaudeROSSI commented on src/provider/CentralServerProvider.tsx
> +    await ReactNativeBlobUtil.config(config).fetch('GET', url, this.buildSecuredHeaders());
> if (config) {
  await ReactNativeBlobUtil.config(config).fetch('GET', url, this.buildSecuredHeaders());
}

2021-06-08 16:08 UTC, AlixH commented on src/provider/CentralServerProvider.tsx
> +    await ReactNativeBlobUtil.config(config).fetch('GET', url, this.buildSecuredHeaders());
done

2021-06-08 16:08 UTC, AlixH commented on src/provider/CentralServerProvider.tsx
> +    let config = {};
done

2021-06-09 06:15 UTC, LucasBrazi06 approved these changes

2021-06-09 06:16 UTC, merged